---
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      sh -c '
        set -euo pipefail
        if [ $(id -u) -ne 1000 ]; then
          exit 1
        fi
        awk --version # gawk
        base64 --version # coreutils
        csvq --version # csvq
        csvsql --version # csvkit
        curl --version # curl
        git --version # git
        grep --version # grep
        pip --version # py3-pip
        python --version # python3
        sed --version # sed
      '
